### ISSUE TITLE
Classroom 5 is very dark

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#10]
Classroom 5 is pretty dark, even with the lights cranked all the way up, which makes it hard to see the whiteboard. 

Would it be possible to get brighter bulbs?

**Comment by adambray** [comment]
(Also, just a heads up the the front lights were aimed at the board, causing glare, so I re-pointed them to be down-ward facing)

**Comment by LivingDATLife** [comment]
Noted! Will look in to this today

**Comment by shanazcw** [comment]
@Campus-Commander @LivingDATLife Can we have an update?

**Comment by Campus-Commander** [comment]
@bmartinowich @adambray @amychoi @ShanazFC I've noticed recently that the dimmers in this classroom are often pushed all the way down. Web Dev mood lighting? Ha- I'll think through some ways to help highlight pushing up the dimmers if needed. And FL/myself will know what to do in case people come to ask. :-)

**Comment by adambray** [comment]
Hey Nyemadi,

You're right that the dimmers do get pushed down, but I (personally) feel that the CR is pretty dark even when the dimmers are all the way up. 

-Adam

**Comment by bmartinowich** [comment]
@Campus-Commander @amychoi Based off @adambray 's observations, do we have any creative solutions here?

**Comment by bmartinowich** [comment]
Planning to see if we can add a brighter bulb in the room, or add additional lights to the track. Will update by next week!

**Comment by bmartinowich** [comment]
@amychoi Reminder to add additional lights to the track

**Comment by amychoi** [comment]
Touching base with global.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

On Mon, Mar 7, 2016 at 11:57 AM, Brian Martinowich <notifications@github.com

**Comment by bmartinowich** [comment]
@amychoi Any update from global? In the meantime, can we add additional lights to the track or install a stronger bulb?

**Comment by amychoi** [comment]
I'm buying 12 more track lights for CR 4-6. It will arrive April 4th.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by bmartinowich** [comment]
@adambray Track lights have arrived. We are planning to install them this week -- should resolve issue, but will update afterwards. cc: @amychoi

**Comment by bmartinowich** [comment]
@adambray Installed track lights, we can add additional lights if needed. Closing this issue cc: @amychoi
