### ISSUE TITLE
PB & J  Stand on the 8th Floor

### ISSUE THREAD

**Issue by jshawl** [ga-dc/campus#11]
![](http://i.giphy.com/l0O9xyxefblWfNWKc.gif)

**Comment by RobertAKARobin** [comment]
:+1:

**Comment by amychoi** [comment]
This has already been in the works for a week or two. It requires restructuring the kitchen, so hang tight.

**Comment by jshawl** [comment]
https://generalassembly.slack.com/archives/dc-wdi7-discussion/p1446666765000129

**Comment by JonRojas** [comment]
Peanut Butter Jelly Time!
