### ISSUE TITLE
Install screen remote holder in new Classrooms

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/campus#12]
Please install a holder in classroom #5 for the screen remote.  This helps to ensure that it does't get lost .  It also gives it a "home", so we know exactly where to look for it when we need it.

**Comment by amychoi** [comment]
Hey Matt,

We have a wall-mounted remote, but it will obstruct the wall which you can
write on...

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by mattscilipoti** [comment]
Ah.  Maybe on a column?

**Comment by LivingDATLife** [comment]
Hey Matt! 

The wall mounted remotes has to be plugged in to the project screen in order to operate. Are you free later today to take a look?

**Comment by Campus-Commander** [comment]
Hey Matt!

The wall mounted remotes has to be plugged in to the project screen in order to operate. Are you free later today to take a look?

**Comment by mattscilipoti** [comment]
Connected?  The one I just used in 6 was not connected. I can meet between 12:30 and 1 today.  I'll be in 4, as class ends, at 12:30.

**Comment by Campus-Commander** [comment]
Hey! 

I have a meeting at that time

We have two ways to operate projector screens: 
1. Using the handheld remotes
2. Using the wall mounted/screen connected remotes

I can ask IT if there are any handheld remote mounts that can be sent to us. The wall mounted remotes were supposed to be an alternative to the handheld version since those tend to get removed from rooms even when there is a wall mounted holder.

**Comment by mattscilipoti** [comment]
Ah.  Communication.  I was looking for a simple wall holder for the hand-held remote - so the hand-held remote had a home (when we weren't actively using it).  We have hand-held remotes, but they are migrating around the room and from room to room.  This hardly ever happened in the other classrooms and I assumed (possibly incorrectly) that the wall mounted holder helped alleviate this.

**Comment by mattscilipoti** [comment]
I was wondering why the connected, wall remote was added to #4.  It decreased our available whiteboard space.  Now, it makes sense - given your translation of our request.

**Comment by JonRojas** [comment]
Will look into the extra remotes we found during the closet cleaning. 

@Campus-Commander @amychoi can we test in CR4 and 5?

**Comment by Campus-Commander** [comment]
I've taken the wall mount down and placed a handheld remote in the room labeled CR 4 @JonRojas

**Comment by amychoi** [comment]
thanks nyemadi!

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

On Mon, Nov 16, 2015 at 12:16 PM, Campus-Commander <notifications@github.com
