### ISSUE TITLE
Fix installed projector in classroom #5

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/campus#13]
We realize that this a known issue.  I just wanted to ensure it was in the new "system", so we could get/give feedback.

Update (11/3): Projector should be available via Apple TV.
Identified issue: HDMI wall cable is not present.

**Comment by amychoi** [comment]
Hey - the actual projector in CR 5 should work. We can make sure by
directly connecting the HDMI/dongle to the projector's input. We have to
install the Apple TV we just received for that classroom, which should
eliminate this problem. The issue with CR 5 is actually the wall plate and
the cord(s) inside of the wall that connect to the projector.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by jshawl** [comment]
The rolly projector was not connecting today

**Comment by amychoi** [comment]
Hey Jesse - sorry about that. Frontlines should've installed Apple TV in
Classroom 5. Please let me know if you have further issues. I can have
Frontlines check the crash cart and cords this evening as well.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by shanazcw** [comment]
@Campus-Commander let's check in on this and close this out if it's resolved.

**Comment by Campus-Commander** [comment]
@bmartinowich @timfoley How are instructors feeling about this projector now? I think the Apple TV has helped but sometimes it is spotty at certain times. Thoughts? 

@ShanazFC @amychoi

**Comment by amychoi** [comment]
The wall plate/HDMI cord from the projector, Apple TV, and the HDMI/dongle cord all work according to Myerconnex who came onsite. All should be good to go.
