### ISSUE TITLE
Projector in Classroom 1 is very dim

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/campus#14]

**Comment by Campus-Commander** [comment]
Hey!

Can you snap a photo for me? I'd like to send it off to global to give them an idea of what is happening

**Comment by RobertAKARobin** [comment]
![cam00144](https://cloud.githubusercontent.com/assets/6268177/10920208/00ec13ae-823d-11e5-9a38-7f6ebbb8ba02.jpg)

**Comment by Campus-Commander** [comment]
Thank you!

**Comment by Campus-Commander** [comment]
Hey! Have you tried the brightness on the projector in the settings? I wonder if it gets switched around with the evening folks? Let me know - thanks!

**Comment by RobertAKARobin** [comment]
Tried turning the brightness up all the way. Still pretty dim!

**Comment by mattscilipoti** [comment]
Checked bulb life with FL this morning: around 3k.

**Comment by Campus-Commander** [comment]
New bulb is being ordered by Global IT team! @mattscilipoti @RobertAKARobin

**Comment by bmartinowich** [comment]
See issue #24 -- closing this issue.
