### ISSUE TITLE
Side vents in Classroom 1 tend to blow hot air, even when set to cool temperatures

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/campus#15]

**Comment by Campus-Commander** [comment]
Hey! Noted- this has been a consistent pain point it - we've reached out to the building numerous times to get this fixed. I'll let you know what comes of this next round of requests

**Comment by RobertAKARobin** [comment]
Thanks!

**Comment by JonRojas** [comment]
@Campus-Commander any updates from the building on this?

**Comment by Campus-Commander** [comment]
@JonRojas is it still happening?

**Comment by timfoley** [comment]
@Campus-Commander As of a few weeks ago yes. It's about to be much less of a problem now that the weather's cooling down, but I am very curious if the building ever took it seriously and tried to fix it. Have we heard anything from them?

**Comment by shanazcw** [comment]
@Campus-Commander Let's update this, and if it's fixed, let's close this out.

**Comment by amychoi** [comment]
Hi Team, I think this is more of a user error issue. You can override it when it's hot/cold air, but we can show how. I've fixed it a couple of times. I will close this issue.

**Comment by timfoley** [comment]
I'd definitely like to see what override options we have. 

This summer, when the thermostat was set as cold as it could go, it would still blow hot air. Does this fix account for that?
