### ISSUE TITLE
Managing external noise leaking into the classrooms

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#17]
I think this has gotten slightly better due to changes in the vents (at least in some classrooms).

But... it's still not uncommon for there to be noise issues from people talking outside, esp in Classroom 1.

I wonder if there are gentle steps we could take, such as signage in the appropriate areas, reminding people that classes may be nearby.

**Comment by adambray** [comment]
Just noting that this was an issue again today with the Marriott event. During breaks, they congregated outside classroom 4, causing some noise issues.

Maybe we could coordinate when large external events are, so at least instructors can plan break or alternate activities when noise may be greater.

**Comment by amychoi** [comment]
Hey Adam - yeah, we were super aware and sorry about that! We spoke to them
about this and moving forward, they will take note to keep their voices low
or move elsewhere :)

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by jshawl** [comment]
@amychoi is there an internal calendar of events? Second Adams comment on planning alternate activities during these times. Let's work together on this issue!

**Comment by amychoi** [comment]
Hi Jesse - we are already working on this with the Production Team. Stay
tuned. We are aiming to have one ready and out for December + moving
forward.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by JonRojas** [comment]
Teams will coordinate events! :)
