### ISSUE TITLE
Classroom 1 Thermostat is programmed at 75ºF

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#18]
It's too hot usually, and every day we have to over-ride the temp at least 3x, because it won't let you over-ride for more than 3 hours.

**Comment by JonRojas** [comment]
@Campus-Commander @amychoi is there a way to set the over-ride or default temperature?

**Comment by Campus-Commander** [comment]
@JonRojas not that I know of off the top of my head- can ask the building for insight

**Comment by shanazcw** [comment]
Is this still an issue? If so, we can work on getting a fan in the classroom if we haven't already.

**Comment by shanazcw** [comment]
Hey @Campus-Commander! Any updates from the building on this issue?

**Comment by Campus-Commander** [comment]
Hi! @ShanazFC  I don't have an update- but will loop back around again after looking in to toggling the thermostat. We do have two fans in this classroom though! So it'll be helpful until we get the final solution :-)

**Comment by bmartinowich** [comment]
No update -- we'll set-up a session on how to use the thermostat. Session is TBD.

**Comment by bmartinowich** [comment]
@amychoi Suggestions and next steps on the info session for how to use the thermostat?

**Comment by Campus-Commander** [comment]
Hey! I'm looking in to the Honeywell thermostat models that we have on campus for any best practices and combine with the knowledge I already have. @bmartinowich

**Comment by bmartinowich** [comment]
@Campus-Commander Were you able to look into the Honeywell materials? Maybe we provide a quick tutorial to major stakeholders on campus? What can we do to close this issue? 
cc: @amychoi

**Comment by Campus-Commander** [comment]
@bmartinowich @amychoi Hi! I've looked through the materials and will write up a few notes that can be posted next to the thermostat. I say let's keep this open even after that though.

**Comment by bmartinowich** [comment]
@Campus-Commander Any update on the write up? Happy to assist here!

**Comment by Campus-Commander** [comment]
None needed- thanks though!

**Comment by bmartinowich** [comment]
@amychoi is working with @Campus-Commander to complete write-up. Should be resolved by next week

**Comment by amychoi** [comment]
@Campus-Commander hey, let's get this one pager up in the classrooms this week and do a quick run through with Brian so that he also knows how to override for WDI

**Comment by bmartinowich** [comment]
@amychoi @Campus-Commander Gentle reminder on the one-pager!

**Comment by amychoi** [comment]
@Campus-Commander please set asides time with Brian + put up one pagers today in the classrooms. It would also be helpful if we do a little one pager for Front Lines.

**Comment by Campus-Commander** [comment]
@amychoi @bmartinowich printed and will be put up during campus flip!

**Comment by bmartinowich** [comment]
Signs have been posted - I missed the meeting, but will play catch-up! Closing issue
