### ISSUE TITLE
Can the screens in Classrooms 4 & 5 be adjusted to stop when they reach a certain height?

### ISSUE THREAD

**Issue by amaseda** [ga-dc/campus#20]
The screens won't stop dropping unless you tell them to with the remote (unlike the ones in Classrooms 1, 2, 3). Thx!

**Comment by amychoi** [comment]
Hey Adrian, with those projectors - to my knowledge - the screens can only
be stopped with the projector when told to. That is the only options we
have with the remotes currently.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by Campus-Commander** [comment]
Or I find a spell... Let me chat with Hermione real quick and get back to you! 

But really: I'll look up the product and confirm :-)

**Comment by amychoi** [comment]
Wingardium levioSTOP!

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by amaseda** [comment]
Sounds good, thanks!
