### ISSUE TITLE
Screen Remote for CR5 is broken

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#21]
I tested the one from CR4 and it works on the CR5 screen, but the CR5 remote doesn't work on either. Turned it into the front desk.

**Comment by amychoi** [comment]
Thanks, Adam - I'll take a look at it when you guys break for lunch...

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by Campus-Commander** [comment]
There is another remote in the safe- we can do a trade and re-label that one for CR5! I'll ping Allyson

**Comment by Campus-Commander** [comment]
Confirming that Allyson will bring the extra screen remote in during lunch break

**Comment by JonRojas** [comment]
Remote replaced

**Comment by adambray** [comment]
Just noting that the remote's gone missing in CR5. Using the one from CR4 in the meantime, and just moving it back and forth.

**Comment by JonRojas** [comment]
Thanks @adambray, I just bought a label maker so we can put labels on things. (rightful homes!)

Put a bird on it. 

![bird](https://cloud.githubusercontent.com/assets/1315364/11223594/bf8623c0-8d3e-11e5-9df5-9f6c6cb7ccd2.gif)

**Comment by JonRojas** [comment]
Will close when things are properly labeled.

**Comment by Campus-Commander** [comment]
I have a remote for you at the front desk when you're on a break. It's labeled awfully but it's the thought that counts right!? @adambray @JonRojas
