### ISSUE TITLE
Could we get Ethernet access in the Cubby Room?

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/campus#23]
I've heard rumors that the Ethernet in this building is CRAZY fast. It would be awesome if there was a designated hook-up spot with cables!

**Comment by Campus-Commander** [comment]
This is an exclusive club- but we'll work to get you access #RumorHasIt @RobertAKARobin

**Comment by shanazcw** [comment]
@Campus-Commander This is so exciting! Any updates?

**Comment by amychoi** [comment]
Ethernet cable is in cubby room @RobertAKARobin
