### ISSUE TITLE
Backup projector (used in Classroom 1) is fuzzy.  Can not bring into sharp focus.

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/campus#25]
The backup projector, currently used in Classroom 1, can not be brought to a sharp focus.  It is hard to read from the back of the class. 
S/N ends with 0190.

Due to this, we request to escalate repair of the "normal" projector: #24.

**Comment by mattscilipoti** [comment]
Tested options.  We moved it back a bit (on rolling podium now) and using HDMI cable (rather than VGA).

**Comment by mattscilipoti** [comment]
It is acceptable.  But, we would still prefer the installed projector.

**Comment by amychoi** [comment]
New bulb is going to be ordered from global which will fix brightness issue.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by shanazcw** [comment]
I'd like to leave this issue open until the new bulb is ordered and installed.

**Comment by mattscilipoti** [comment]
I created this issue to clear up an issue with the temporary projector.  The installed projector is covered by #24.  I recommending closing this duplicate.
