### ISSUE TITLE
Port-a-projector in classroom 5

### ISSUE THREAD

**Issue by jshawl** [ga-dc/campus#26]
Is the overhead projector here broken?

**Comment by amychoi** [comment]
Hey Jesse - thanks for the note. It's not technically broken, rather the
cable in the wall from the projector to the wall plate is and we are still
assessing how that can be fixed as it would require going through the wall.
The wall plate can be temperamental hence why we leave the crash cart in
there for usage. Is that not working out right now in the meantime?

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by jshawl** [comment]
It's working well! Just wanted to log it for seventh generation / team documentation.

**Comment by shanazcw** [comment]
+1 for seventh generation / team documentation! :D

**Comment by shanazcw** [comment]
Hey @amychoi -- can you update the team on the projector status and our plan of action?

**Comment by bmartinowich** [comment]
@ShanazFC Classroom 5 projector is working. Closing issue based of conversation with @JonRojas and @amychoi
