### ISSUE TITLE
Is it possible to run a small server on the GA network?

### ISSUE THREAD

**Issue by jshawl** [ga-dc/campus#27]
interested in either:

1) Modifying DNS entries to point to a local server
2) Plugging a raspi into the network so only people on the wifi can access that server

**Comment by shanazcw** [comment]
@jshawl I have no idea, so I've pinged our IT department! Keeping this thread open until we have an answer from Ian! :)

**Comment by amychoi** [comment]
@ShanazFC Nyemadi has already connected with IT about this with Jesse.

**Comment by jshawl** [comment]
1776 has a known static IP: 50.200.196.50 We'll use this instead of running a small server. :+1:
