### ISSUE TITLE
Screen Cut-Off in Rm 4

### ISSUE THREAD

**Issue by timfoley** [ga-dc/campus#28]
Presentations in Rm4 are cut off by the projector. I looks like we need to fiddle with the zoom settings on the projector itself and potentially test with a few computers. This has happened across a few different computers. I just heard about this from my DGM instructors.

**Comment by shanazcw** [comment]
@amychoi Have the new front lines team members been trained on projector troubleshooting?

**Comment by amychoi** [comment]
Yep.

**Comment by amychoi** [comment]
Hey Tim - I'll look @ this today before class. Thx for letting us know.

**Comment by amychoi** [comment]
@timfoley I just fixed the aspect ratio. It was on 16:9 and I reverted it back to auto. I tested with my laptop and it was good to go. It was a projector setting.
