### ISSUE TITLE
Attach cupholders to podia

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#29]
Maybe some that can screw on to the bottom and just out?

**Comment by JonRojas** [comment]
@adambray, do you think something like this would work?

[clip-on cupholder](http://www.ebay.com/itm/Home-Office-Use-Drink-Cup-Party-Coffee-Glass-Cup-Holder-Stand-Clip-Desk-Table-/281758367389)

**Comment by amychoi** [comment]
I was actually thinking the ones that hook to the side might be better
because of the way the podiums are...

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by JonRojas** [comment]
👍😄

**Comment by adambray** [comment]
Yeah, I think something that hooks over would be more secure

**Comment by amychoi** [comment]
I'll look into some options and see what we can bring onto campus next
week... stay tuned.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by bmartinowich** [comment]
@amychoi Just spoke with @adambray about this issue. We can close it, but moving forward I think the instructors would like to be consulted more about the podia decisions or other stuff that will impact the classroom experience. :+1:
