### ISSUE TITLE
Printer in Classroom 2

### ISSUE THREAD

**Issue by alfonsobravo** [ga-dc/campus#32]
The printer in CR2 was apparently between problematic to not working at all. Not sure if its ink or mechanical but would appreciate it being looked at and serviced if needed.

**Comment by Campus-Commander** [comment]
I'll take a look at it this afternoon- thanks for flagging!

**Comment by Campus-Commander** [comment]
Hey! Looks like toner may have been the issue- I changed the ones that were low (black & yellow). Lemme know if the printer keeps causing problems!

**Comment by alfonsobravo** [comment]
Thank you!

**Comment by Campus-Commander** [comment]
Sure thing!

**Comment by bmartinowich** [comment]
@alfonsobravo @Campus-Commander Sounds like this issue is resolved. Can either of you confirm?

**Comment by Campus-Commander** [comment]
@bmartinowich I'll leave this one for @alfonsobravo to decide. This time around was a toner issue- but printers are finicky so who knows what could happen next!

**Comment by alfonsobravo** [comment]
Fixed! Thanks!

On Thu, Jan 28, 2016 at 3:55 PM, Campus-Commander notifications@github.com
wrote:

> @bmartinowich https://github.com/bmartinowich I'll leave this one for
> Alfonso to decide. This time around was a toner issue- but printers are
> finicky so who knows what could happen next!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/campus/issues/32#issuecomment-176412055.

## 

*Alfonso Bravo *| Education Programs Producer
General Assembly http://generalassemb.ly | 1133 15th St. NW | Washington,
D.C.
alfonso@ga.co | 202-264-0188 http://+12022640188

**Comment by alfonsobravo** [comment]
Fixed! Thanks!
