### ISSUE TITLE
Can we ask Front Lines to *not* clean off whiteboards until like 4:30 or 5?

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/campus#33]
We asked our students to write things on the back wall of Classroom 5 over the course of the day as a reflection on this WDI. Someone erased all of it around noon. :( I don't know whether it was Front Lines, and even if it was we totally can't fault them because we should have put up a "Do Not Erase" sign or something. But it may be a good idea to have a directive in place along these lines!

**Comment by Campus-Commander** [comment]
Oh no :-( Not sure who did that- my apologies if it was someone from my team

**Comment by RobertAKARobin** [comment]
I meant "we totally can't fault them," not "we can't totally fault them"!

**Comment by bmartinowich** [comment]
@Campus-Commander Can we add this to the Front Lines agenda list? I'll close this issue, once it's resolved for future instances cc: @RobertAKARobin

**Comment by Campus-Commander** [comment]
@bmartinowich @RobertAKARobin Yup for sure it'll be noted! Classroom flipping occurs in the morning and then post 5:30pm- so noon is an oddity for team experience to wipe down a classroom
