### ISSUE TITLE
Pod maintenance

### ISSUE THREAD

**Issue by alfonsobravo** [ga-dc/campus#34]
I just had a student find a string cheese wrapped left in one of the pods, and there's also a fair amount of hair buildup / crumbs etc. at any point in time. Can we have either a front-lines process (and maybe get them a dustbuster or something), or communicate with the cleaning staff about them? "Pods get gross" has come up more than once in feedback. Thank you!

**Comment by Campus-Commander** [comment]
Hey! Thanks for letting me know about this. There was a clear task given to FL who worked last night to dirt devil the denim pods and clear them out. Sorry your student had to deal with that!

**Comment by mattscilipoti** [comment]
Thanks for the quick response to this need.
I would love to see a response that talks to the long-term support questions that were raised (in response to student feedback).

**Comment by bmartinowich** [comment]
@Campus-Commander Has this been officially resolved? I'd like to close the issue if @alfonsobravo agrees that it's good to go!

**Comment by Campus-Commander** [comment]
Hey! @bmartinowich - My vote is to keep this issue open in case other pod problems arise. What are your thoughts @alfonsobravo ?

**Comment by bmartinowich** [comment]
Closing Issue based off conversation with @amychoi and @JonRojas
