### ISSUE TITLE
Water Fountain has funny taste and gives cotton mouth

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#35]

**Comment by adambray** [comment]
This is the one in the front kitchen, have gotten reports from multiple people. Maybe it just needs to be flushed.

**Comment by JonRojas** [comment]
Thanks!

@amychoi is contacting CoolerSupport to get it checked out. In the meantime, only drink 🍺

**Comment by adambray** [comment]
It might be worth getting a few pitchers and just filling them up and dumping them to flush the cooler lines out. 

I've had similar problems when moving into an apartment that'd been empty for 2 months, and doing this made a big improvement.

**Comment by amychoi** [comment]
They are coming to service the water cooler in 1-3 business days.

**Comment by bmartinowich** [comment]
Quick update: We've posted a sign and cooler support is coming this week.

**Comment by bmartinowich** [comment]
@amychoi Fixed the water cooler - closing issue
