### ISSUE TITLE
Wobbly table in classroom 4

### ISSUE THREAD

**Issue by thatdevgirl** [ga-dc/campus#36]
I noticed this Tuesday evening.  One of the tables is really wobbly in classroom 4.  It was the 2nd from the windows in the 2nd row.

**Comment by Campus-Commander** [comment]
@thatdevgirl @amychoi @bmartinowich Great- we'll take a look at this today. Thanks for flagging!

**Comment by amychoi** [comment]
@Campus-Commander can we get the extra table leg thingys and make sure this is donezo?

**Comment by bmartinowich** [comment]
@Campus-Commander Is this resolved? Let me know if you have an update :)

**Comment by thatdevgirl** [comment]
I _think_ so, but I can test when I'm in class tomorrow night.

**Comment by thatdevgirl** [comment]
I had my class wiggle all the tables last night and they all seemed fine.  :)  Marking this as closed.
