### ISSUE TITLE
Projector in Classroom 5 occasionally flickers and makes a static burst

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/campus#37]

**Comment by JonRojas** [comment]
@RobertAKARobin we're using CR5 now and I will look out for this. Was it happening with the cable or AppleTV?

**Comment by amychoi** [comment]
We had the MyerConnex guys test it again and he had no issue. If you can
clarify which it was with (cable or Apple TV) that will definitely help us
diagnose the problem.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by bmartinowich** [comment]
@RobertAKARobin Do you have an update on this issue? We were in Classroom 5 today, and I didn't see any issues. Wanted to check with you first though...

**Comment by bmartinowich** [comment]
@RobertAKARobin Just checking in again, do you have any update on this? It's my understanding that this might have be resolved, since all projectors have been replaced on campus.

**Comment by amychoi** [comment]
When MyersConnex came back to remount CR 3's projector a few weeks ago, I
asked them to look at this classroom again and test it and it was fine.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

On Wed, Feb 17, 2016 at 4:50 PM, Brian Martinowich <notifications@github.com

**Comment by RobertAKARobin** [comment]
Hey, I haven't used CR5 in a long time and so am unsure. Sorry.

**Comment by bmartinowich** [comment]
Planning to test this out today on my laptop. Will close if resolved.

**Comment by bmartinowich** [comment]
Tested out today. Did notice the flicker, working with @amychoi to resolve. Looks like it might be the wall outlet.

**Comment by bmartinowich** [comment]
Confirmed with @amychoi that this is resolved. Changed out the cord and works fine. (might encounter a slight pause when switching between inputs, but it's normal)
