### ISSUE TITLE
CR2 - ~4 Lightbulbs Out

### ISSUE THREAD

**Issue by alfonsobravo** [ga-dc/campus#38]
Will be recording presentations in there and classroom is a bit dark. Would appreciate bulbs being replaced when possible!

**Comment by Campus-Commander** [comment]
@alfonsobravo Hey!  @amychoi are working on learning how to get bulbs in and out of these classrooms - we'll loop back around!

**Comment by bmartinowich** [comment]
@Campus-Commander @amychoi Any update on these bulbs in CR4?

**Comment by Campus-Commander** [comment]
@bmartinowich @amychoi Tim and I made an interesting discovery - stay tuned for an update. I'll be checking lights tonight!

**Comment by bmartinowich** [comment]
@Campus-Commander Can we close this out, based off your interesting discovery?

**Comment by bmartinowich** [comment]
@amychoi @Campus-Commander Closing this out, since it's resolved.
