### ISSUE TITLE
CR3 - Projector Settings Messed up on HDMI Cable Input

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#39]
Airplay works ok, but is unreliable, so that's not a great fallback.

When using HDMI, the projector's aspect ratio get all messed up and stretch the screen. Switching to Anamorphic 2 fixes the aspect ratio, but the resolution gets reported as something wonky and tall and narrow, like 800x1600, so the top and bottom of the screen are cut off.

**Comment by Campus-Commander** [comment]
@adambray @amychoi Hey! We'll take a look at this when we flip classrooms for the evening.

**Comment by adambray** [comment]
Ok, thanks! FWIW, we're on break until 2pm today.

**Comment by Campus-Commander** [comment]
@adambray I have a 1:00pm meeting and then a backlog of items I need to wrap up. If you'd like my attention before that- I can switch some items around.

**Comment by bmartinowich** [comment]
@adambray After speaking with @amychoi it sounds like it might have been your computer resolution settings, when using the projector. Let me know if you're available this week to test everything out!

**Comment by adambray** [comment]
Don't think it was my computer, as we had issues with 2 or 3 other computers we tested with. I'll play with it during lunch today and see if I can reproduce.

**Comment by bmartinowich** [comment]
@adambray We just tested two computers and cords in classroom 3 and both work properly. I'm going to close this issue, but let's sync up at some point today!
