### ISSUE TITLE
Bathroom Cleaning before PT Classes

### ISSUE THREAD

**Issue by timfoley** [ga-dc/campus#40]
Just about every single Mid- and End-of-Course survey I receive has a few strong complaints about bathroom cleanliness. Here's a representative sample:

> One specific complaint: the bathrooms were consistently dirty. I don't think I ever stepped into a stall during my entire time at GA that wasn't covered in unmentionable bodily fluids. Because my course was at night, maybe the cleaning didn't happen as frequently? But they were honestly impressively gross. 

From my own experience, this isn't that much of an exaggeration. 

What's the current cleaning schedule? I often see them taking out the trash during the day, but do they clean the floors/toilets if necessary? Whatever they're currently doing isn't enough for a lot of our students.

**Comment by amychoi** [comment]
Don't know the schedule - but pinged Shahier and I've talked to him about
this complaint before. Stay tuned.

**Comment by timfoley** [comment]
Thanks Amy!

**Comment by amychoi** [comment]
Building told us that cleaning is scheduled 3x a day, but I challenged that since we always see the bathrooms dirty. They are also working on getting us a quote for hand dryers to eliminate paper towel waste. Will talk to Shahier again this week.

**Comment by bmartinowich** [comment]
@amychoi Any update on the quote or from the conversation with Shahier on this?

**Comment by amychoi** [comment]
Beltway came and did a deep cleaning of the bathrooms last Friday. We should have hand dryers installed by the end of next week, according to building management.

**Comment by bmartinowich** [comment]
Sounds like this is resolved, with the hand dryers being installed @amychoi will confirm
