### ISSUE TITLE
CR4 projector - HDMI cable/port not working

### ISSUE THREAD

**Issue by jshawl** [ga-dc/campus#41]
cannot screencast lessons

**Comment by bmartinowich** [comment]
@jshawl Did we try another cord or dongle? I'll speak with front lines about this make sure we get this resolved ASAP cc: @amychoi

**Comment by thatdevgirl** [comment]
I've tried a couple of different HDMI cords in CR4 and that connection never seems to work.  I've just been using airplay.

**Comment by bmartinowich** [comment]
Thanks @thatdevgirl! @amychoi and I will check the cords today during lunch and provide everyone with an update.

**Comment by RobertAKARobin** [comment]
It didn't work today. Solution: wedge a pen beneath the crate and the cable where it connects to the computer.

**Comment by bmartinowich** [comment]
Tested out with @amychoi with two different connectors and worked properly. Will close this issue, but @RobertAKARobin and @thatdevgirl please let us know if you are still having issues! :+1:

**Comment by thatdevgirl** [comment]
I no longer have class in CR4, so I'll leave the in-class testing up to @RobertAKARobin.  :)  Thanks for fixing!
