### ISSUE TITLE
Tell Shahier to Buy Toner in Bulk

### ISSUE THREAD

**Issue by timfoley** [ga-dc/campus#42]
It's ridiculous! They should never run out...

**Comment by Campus-Commander** [comment]
@amychoi @timfoley While we can make a suggestion, I don't know that we can dictate how they spend money and when they do it? Amy would you like to ask him about bulk toner or should I?

**Comment by timfoley** [comment]
I apologize for exaggerating there; I was feeling pretty emotional at the time :P . We **can** tell him how disappointing it is that it appears they wait until the printer runs out of toner to order more, and that it takes more than a few days for the replacement to arrive. The same thing happened last month.

**Comment by Campus-Commander** [comment]
@timfoley @amychoi haha no worries- it is frustrating that they do not replenish as often as they should. I think the printers upstairs get a bit more attention from them but that's not fun to have to walk all the way up consistently. I'll let you know what comes of that conversation

**Comment by timfoley** [comment]
Thanks!

**Comment by timfoley** [comment]
It's been replaced! And Shaheir (SP?) said they generally have more on hand, but they ran out this time... so I'll just make sure to whine extra loud next time this happens.
