### ISSUE TITLE
HDMI Wall Plate in CR3 is extremely loose

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#43]
Even just making contact with the cable with your body will cause the cable to disconnect. It's exacerbated by it's location relative to the podium / screen, i.e. you have to keep walking over it to get from behind the podium.

**Comment by Campus-Commander** [comment]
Hey @adambray  noted. @amychoi can we have someone come out?

**Comment by adambray** [comment]
Just a note, what really prompted me to file this issue was that Kevin has had it come out at least 5x during his afternoon lesson today.

**Comment by adambray** [comment]
(and I've had it happen to me quite a bit lately too.)

**Comment by Campus-Commander** [comment]
Thanks for flagging!

**Comment by bmartinowich** [comment]
Note: The wall plate is not loose, however the HDMI input is a little more flexible. Tested out on laptop and still works. Just need to be careful with walking around cord.
