### ISSUE TITLE
CR1 Projector Not working

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#45]
Tried multiple computers

**Comment by amychoi** [comment]
Fixed this. HDMI ports in projector were backwards (Apple TV is supposed to
be in HDMI and display is supposed to be in HDMI 2). Works now.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by amychoi** [comment]
Spoke too soon. HDMI2 isn't working :'(

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by bmartinowich** [comment]
Planning to schedule an additional session for this cc: @amychoi

**Comment by bmartinowich** [comment]
Tested out additional cords and connectors with @amychoi - seems to be an issue with HDMI port one, might be the wall plate or the cord within the wall. Please use Airplay in the meantime. @amychoi Will update on next steps

**Comment by JonRojas** [comment]
@bmartinowich and @amychoi as a heads up, we have instructors that use Linux or Windows and are not able to connect via Airplay. Do we have a timeline for being able to use cords?

Thanks!

**Comment by amychoi** [comment]
We have an extra projector on a podium in this room that works and should
be compatible for them. Airplay is also dicey.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by bmartinowich** [comment]
@amychoi Scheduling meeting with global to discuss solution for HDMI cord. Will update with next steps

**Comment by adambray** [comment]
Just an update that we're able to swap the cables today to get the wall plate working with the built-in room projector, but yeah, it seems the other port on the projector is broken. 

I can't speak for evening classes, but assuming we have a long enough cable, WDI seems to be ok without the crash cart projector for the time being.

**Comment by bmartinowich** [comment]
@amychoi Any update on next steps? Has this one been resolved?

**Comment by bmartinowich** [comment]
Bought additional supplies to resolve this issue (wall plates and cables). Will arrive by Thurs/Friday. @amychoi @adambray

**Comment by bmartinowich** [comment]
@adambray Replaced the wall plate in CR 1 today, I tested w/ Andy - but this should be resolved. Will keep open until you confirm cc: @amychoi

**Comment by bmartinowich** [comment]
Replaced wall mount with new cord system and tested with laptop. Worked successfully, marking as resolved
