### ISSUE TITLE
CR6 - Possible Projector Issue

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#46]
I arrived to class right on time, so I couldn't ask the instructor to troubleshoot, but the screen has a very strong green tint. I think this is usually a cable / connection issue, but as I mentioned, haven't been able to help him troubleshoot, and won't be able to tonight.

**Comment by Campus-Commander** [comment]
@adambray @amychoi will have the front littles take a look this evening

**Comment by adambray** [comment]
Thanks! Just a note it got better at one point when we jiggled the cable, then later it went back to a greenish tint.

**Comment by Campus-Commander** [comment]
Thanks for that insight!

**Comment by bmartinowich** [comment]
Going to review today after blastoff - will have an update soon

**Comment by bmartinowich** [comment]
@adambray Are you using HDMI port? I'd like to suggest using the dongle moving forward. I tested this out in CR6 today and seemed to work fine. Problem is not with the wall plate or the projector, but rather the HDMI port itself.

**Comment by bmartinowich** [comment]
@adambray Just wanted to follow up here, did you try the dongle? This might be a mute point, but still wanted to follow up...

**Comment by adambray** [comment]
@bmartinowich Pretty sure adding an additional connector will almost never solve the issue. I.e. if the issue is present in the signal path Computer -> HDMI Cable -> HDMI Wall Plate -> Internal Cable -> Projector, then it'll still be a problem when you add a dongle and have Computer -> Dongle -> HDMI Cable -> HDMI Wall Plate -> Internal Cable -> Projector.

I haven't tried with a dongle lately, but the last time I had this problem personally, it was jiggling at the wall plate that fixed / exacerbated it.

**Comment by bmartinowich** [comment]
@adambray Planning to replace the wall plates for classrooms. We are placing the order this week, and will have an update afterwards. Stay tuned cc: @amychoi

**Comment by bmartinowich** [comment]
Bought additional supplies to resolve this issue (wall plates and cables). Will arrive by Thurs/Friday. @amychoi @adambray

**Comment by bmartinowich** [comment]
Replaced wall mount with new cord system and tested with laptop. Worked successfully, marking as resolved
