### ISSUE TITLE
CR2 - HDMI Wall Outlet and Project Tint 

### ISSUE THREAD

**Issue by pjsheeran** [ga-dc/campus#47]
@amychoi @Campus-Commander 

Having issues getting any kind of connection out of the wall plug. Cord is loose when plugging into wall so connection might not be optimal.

Also, there is a weird blue tint to the projector now. Makes Faz sad. #

**Comment by Campus-Commander** [comment]
And that makes me sad too!

**Comment by amychoi** [comment]
Nyemadi - let's schedule time today during lunch to troubleshoot CR 2 for
UXDI

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by bmartinowich** [comment]
@amychoi were you able to meet with @Campus-Commander last week to address? Any update?

**Comment by alfonsobravo** [comment]
@amychoi @Campus-Commander @bmartinowich any updates on this? having a blurry and off-color projector during visual design week has been a tad less than ideal.  :|

**Comment by timfoley** [comment]
My FEWD instructors have also noticed the issue. They've said that the plug in the wall is loose, and they repeatedly lose their connection. They use AirPlay to mitigate, but one of my instructors will be using a PC in his next session, so that won't be an option.

**Comment by bmartinowich** [comment]
@amychoi @Campus-Commander Seems to be an on going issue, any update here? I'm also going to merge the other CR2 issue into this one. 

https://github.com/ga-dc/campus/issues/48 CR2 - Air play and WiFi combo

**Comment by bmartinowich** [comment]
@pjsheeran @timfoley @alfonsobravo We are working to replace the wall plates with Tim's most recent suggestion. We are placing the order this week and will provide everyone with an update afterwards. cc: @amychoi

**Comment by bmartinowich** [comment]
@pjsheeran @timfoley @alfonsobravo Wall plate issue has been tested and resolved! Please let us know if you have any additional concerns!
