### ISSUE TITLE
CR2 - Air play and WiFi combo

### ISSUE THREAD

**Issue by fazthepersian** [ga-dc/campus#48]
Got

 kicked off 4 times today in a span of 2.5 hours. I don't believe this occurs in the other rooms as often. So not sure if it's only a wifi issue or not. 
But wifi is certainly slower when the lose of connection happens more frequently.

**Comment by JonRojas** [comment]
@fazthepersian definitely a wifi issue. Apple TVs are now hard-wired. Concentus was on campus last night attempting to fix the network.

**Comment by bmartinowich** [comment]
@fazthepersian is this still an on-going issue? Happy to jump in and test this out today. Let us know, thanks! cc: @amychoi @Campus-Commander

**Comment by bmartinowich** [comment]
Closing and merging w/ https://github.com/ga-dc/campus/issues/47
