### ISSUE TITLE
There was a big tub of AWESOME multigrain pretzels in the quiet room a few months ago. Any chance we could get some more?

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/campus#49]
I'll always remember them. #NeverForget

**Comment by amychoi** [comment]
You're hilarious for putting this in github and for #NeverForget - yes, we
can :)

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by bmartinowich** [comment]
Since this issue is so amazing, I am going to close it @amychoi @RobertAKARobin
