### ISSUE TITLE
Recycling?

### ISSUE THREAD

**Issue by timfoley** [ga-dc/campus#50]
I've heard that our building doesn't actually recycle. Is that the case?

**Comment by Campus-Commander** [comment]
@timfoley @amychoi Not sure what the building does with the trash but can ask Shahier if he knows. Would be disappointing if they don't.

**Comment by Campus-Commander** [comment]
1776 to look at building recycling and share a composting program they are starting

**Comment by bmartinowich** [comment]
@Campus-Commander @amychoi Any update on this? When are we planning to meet with Shahier?

**Comment by bmartinowich** [comment]
Confirmed that 1776 does not currently recycle. That said, they are looking into alternative options. Closing issue for now, might suggest that we create a slack group for anyone that is interested in talking more about this.
