### ISSUE TITLE
CR4 - Airplay and WiFi issue

### ISSUE THREAD

**Issue by thatdevgirl** [ga-dc/campus#51]
When I am in CR4 (Tuesday and Thursday evenings), I use Airplay over the WiFi to project.  Every so often I lose that connection. My screen will freeze or become sluggish (i.e. I don't completely have control over my mouse) and then the projection goes away altogether.  I have been able to re-establish the connection after the Airplay disconnects, but it is really distracting when I am in the process of losing the connection - particularly when it is at the point where it starts freezing and becomes sluggish.  

I cannot reliably reproduce - it just randomly happens.  Any advice?  Thanks!

**Comment by bmartinowich** [comment]
@thatdevgirl the issue here is actually the network rather than the Airplay device. That said, have you tried to connect directly using the HDMI cord? This should resolve the issue, but we have been addressing the wifi regularly here on campus. Let me know if you have issues with the HDMI cord! cc: @amychoi

**Comment by thatdevgirl** [comment]
Is the HDMI cord in CR4 fixed?  The last time I tried to use it, I was unable to connect at all to the projector (even after swapping out the cord for a new one), which is why I started using Airplay in the first place.  I have class tomorrow night (Tuesday); I will try again then.

**Comment by thatdevgirl** [comment]
Updated: I tried the HDMI cord in class yesterday.  It worked great for the first hour and then the picture froze up and eventually stopped projecting.  (Note: I run an app on my computer while I am projecting called "Caffeine", which prevents my computer from falling asleep, so my computer potentially falling asleep and cutting off the display is not a potential cause.)

I unplugged and then replugged the HDMI cable from both my computer and the wall.  When I did that, the picture came back, but it was purple.

I went back to Airplay after that, but had a bunch of issues again with the projection freezing and loosing the picture altogether.  

If the issue is actually with the wireless, is it possible to get a wired connection in CR4?

@amychoi @bmartinowich

**Comment by thatdevgirl** [comment]
Another case for a wired connection: I tried to pull up https://gallery.generalassemb.ly/ at the end of class to show my students (we're starting to talk about final projects) and the connection was so slow, it did not pull all of the CSS for the page, which made the page look seriously broken.

**Comment by thatdevgirl** [comment]
Another update - I have been using the new HDMI connection and it works great!  

Just a note to other users of the room: Sometimes I do have issues with the connection not quite making it - either I do not get a picture or the picture is purple (yes... seriously. :) ).  If I unplug and then replug the cable in, I am able to project (with normal colors). This is an occasional issue that does remedy itself after reconnecting, so not a big deal, but I thought is note-worthy.

Thanks for putting in the new connection - so much better than Airplay!  :)
