### ISSUE TITLE
CR3 - HDMI port not working

### ISSUE THREAD

**Issue by jshawl** [ga-dc/campus#52]

**Comment by bmartinowich** [comment]
@jshawl Can you provide additional context? is it the port or cord? happy to test this out to resolve!

**Comment by bmartinowich** [comment]
@amychoi FYI ^^

**Comment by bmartinowich** [comment]
Bought additional supplies to resolve this issue. Will arrive by Thurs/Friday.

**Comment by bmartinowich** [comment]
Replaced wall mount with new cord system and tested with laptop. Worked successfully, marking as resolved
