### ISSUE TITLE
Proposal to Fix Wall-Plate HMDI Issues

### ISSUE THREAD

**Issue by timfoley** [ga-dc/campus#53]
# The Problem

The wall plates we have won't stand up to our routine wear and tear. They've become way too loose, and the HMDI cables disconnect very easily. 
# A Solution

Rather than plugging into a wall _socket_, which will eventually just loosen up again, I think we would be much better off plugging into a short _cable_ coming out of the wall. That way, the connection has plenty of slack to move around, and if anything breaks, we can just replace the short cable. If that sounds a bit confusing, check out the diagram below:
![img_20160329_191901](https://cloud.githubusercontent.com/assets/2591447/14148248/b9823558-f66c-11e5-9b1b-4bbc724b0be8.jpg)
## Shopping List
1. [HMDI Female-to-Female Coupler](http://www.amazon.com/Cable-Matters-Plated-Female-Coupler/dp/B00CJHXY0U/) 2-pack for $10.78 [**A**]
   ![HDMI Female Coupler](http://ecx.images-amazon.com/images/I/815IuVkG2tL._SL1500_.jpg)
2. Replacement [Wall Plate with Cable Port](http://www.amazon.com/Datacomm-450001WH-2-Recessed-Voltage-Plate/dp/B00I4DJHUE/) 2-pack for $10.78 (and here's an [alternate style](http://www.amazon.com/gp/product/B00UZG0T00/) ) [**B**] 
   ![Wall Port](http://ecx.images-amazon.com/images/I/61ECtuFQKuL._SL1000_.jpg)
3. [8" HMDI Cable](http://www.amazon.com/Monoprice-8inch-28AWG-Speed-Female/dp/B004C4XR00/) 2-pack for $9.95 [**C**]
   ![HMDI Cable](http://ecx.images-amazon.com/images/I/61ghBLW7u9L._SL1500_.jpg)

**Comment by bmartinowich** [comment]
@timfoley live shout out to you for this! @amychoi is planning to place the order this week. Will have an update soon!

**Comment by bmartinowich** [comment]
Tested this process with @timfoley today in CR2 - issue has been resolved!

**Comment by timfoley** [comment]
![plug](https://cloud.githubusercontent.com/assets/2591447/14436161/6265cc4a-ffe9-11e5-9862-7293da018f87.jpg)
