### ISSUE TITLE
Internet issues

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#7]
Put em here!

**Comment by adambray** [comment]
Thursday 10/29, 3:47 in classroom 5. Very Slow

**Comment by amychoi** [comment]
Thanks, Adam. Sent this to global.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by Campus-Commander** [comment]
Thanks Amy!

**Comment by adambray** [comment]
Just noting additional issues as instructed by production, in case it helps diagnose:
- Wed, 11/04, ~9:30am, Classroom 5
  - connection to ga-guest extremely slow, loading a web page during a lesson took ~45 seconds
- Wed, 11/04, ~10:15am, Classroom 6
  - speed issues on GA-Guest and 1176 member 8, made video conferencing very difficult. worked after reconnecting 2x.

**Comment by adambray** [comment]
Wed, 11/04, 4:54, Classroom 4
unresponsive on 1776-Member-8. Had to disconnect and reconnect to get access

**Comment by amychoi** [comment]
Relayed to Global IT team. Please run wireless diagnostics if possible and
send over tar file to us.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by jshawl** [comment]
Took 2 minutes to connect to ga-guest in classroom 5 this morning.

**Comment by amychoi** [comment]
Thanks - if this happens again, can you run a wireless diagnostic by
holding down the option button and clicking on the wireless icon on the mac
toolbar and click "Open Wireless Diagnostics" and run a diagnostics report
and sent over to us :)

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by timfoley** [comment]
I just had GA-Guest cut out 3 times during a 40 minute meeting over Hangouts. It took ~30-40 seconds to reconnect each time. Didn't have a chance to run a wireless diagnostic at the time, but I can't imagine it would be any different from these previous ones I submitted.

**Comment by amychoi** [comment]
Thanks, submitted to IT team.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by JonRojas** [comment]
GA IT is investigating the issue. If you continue to have issues, please see [Amy's Internet Issues document](https://slack-files.com/files-pri-safe/T024JRAUL-F0EKNGGQY/wifi_problems.pdf?c=1447692543-ac473abd847403ab09027d52485fd122e5f7fcfc)
