### ISSUE TITLE
ID Card doesn't work for weekend access

### ISSUE THREAD

**Issue by adambray** [ga-dc/campus#9]
@amychoi I had to come in this morning for observations, and my ID doesn't work on the front door. Can you help in getting it activated? In case you need it, the numbers printed on it are:

16-00642 11101163827-1A

**Comment by amychoi** [comment]
Can you slack me a picture of the back of your ID and I will take care of this?

Amy Choi | Experience Coordinator
General Assembly | 1133 15th St. NW | Washington, D.C.
amy.choi@ga.co | 202-823-3874

**Comment by adambray** [comment]
Thanks Amy. I got my new card!
